### ISSUE TITLE
Avoiding hard-coded parameters

### ISSUE THREAD

**Issue by mrtamm** [GenomicDataInfrastructure/starter-kit-beacon2-ri-api#5]
As I was following [data beaconization tutorial](https://b2ri-documentation.readthedocs.io/en/latest/tutorial-data-beaconization/#step-4), I got stuck when I tried to execute command `docker exec beacon python beacon/db/extract_filtering_terms.py`. The reason was that I had configured different values for the mongo database (hostname, username, password). However, the script was not using the configuration file I provided at `/beacon/beacon/conf.py`, so it did not know how to properly connect to mongo database.

I don't have a solution yet for this problem, other than to hard-code my mongo connection string for the local build. So I am starting a discussion on how to potentially fix this for everyone.

I noticed that the `beacon/db/__init__.py` actually initialises the mongo-client using configuration values. So maybe execute `beacon.db.extract_filtering_terms` as a module? However, currently this module solution does not work due to import `from utils` (which I think is not used at all in the same file). Also, switching to module-approach may require updating the referred tutorial so that users would know the new command.

I also noticed that `beacon/utils/auth.py` file refers to a fixed permissions server, which should be based on a configuration value.

Any ideas on how to fix these issues?

**Comment by costero-e** [comment]
Hi Martti,
at docker-compose file is where you tune your mongodb credentials and configuration. In theory, if you change this part:
```
  db:
    image: mongo:5
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: beacon
``` 
Then, you only have to modify conf.py file as you said with the values you have in the docker-compose file
```
database_host = '127.0.0.1'
database_port = 27017
database_user = 'root'
database_password = 'example'
database_name = 'beacon'
database_auth_source = 'admin'
``` 

Does this help you enough?
